POST http://localhost:3500/v1.0/publish/pubsub/new
Content-Type: application/json

{
    "Summary": "Grey",
    "Location": "44256",
    "TemperatureC": "0"
}

###

GET http://localhost:3500/v1.0/invoke/myapp/method/WeatherForecast/44256